name: myfirst-action
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Print "Greetings"
      run: echo "HELLO"
    - name: Print name
      run: echo "Hello, ${{vars.MY_NAME}}"
    

  surname:
    needs: myfirstjob
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Print surname
      run: echo "Surname - ${{secrets.MY_SURNAME}}" | sed 's/./& /g'
    

