name: myfirst-action
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
    - name: Print "Greetings"
      run: echo "HELLO"
    - name: Print "Congratulations"
      run: echo "BRUH"
